
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDECOLUMN COMMA DIVIDE EQUALS EXIT FALSE FLOAT LPAREN MINUS MULTIPLY NUMBER PLUS RPAREN STRING TABLE_C TABLE_R TRUE report_item_enable report_item_type_enable\n    calc : expression\n         | empty\n    \n    expression : expression MULTIPLY expression\n               | expression DIVIDE expression\n               | expression PLUS expression\n               | expression MINUS expression\n    \n    expression : NUMBER\n               | FLOAT\n    \n    expression : TABLE_C column\n    \n    expression : TABLE_R column\n    \n    column : STRING\n            | STRING COMMA column\n    \n    boolean : FALSE\n            | TRUE\n    \n    expression : report_item_type_enable boolean\n                        | report_item_enable boolean \n    \n    expression : EXIT\n    \n    empty :\n    '
    
_lr_action_items = {'NUMBER':([0,11,12,13,14,],[4,4,4,4,4,]),'FLOAT':([0,11,12,13,14,],[5,5,5,5,5,]),'TABLE_C':([0,11,12,13,14,],[6,6,6,6,6,]),'TABLE_R':([0,11,12,13,14,],[7,7,7,7,7,]),'report_item_type_enable':([0,11,12,13,14,],[8,8,8,8,8,]),'report_item_enable':([0,11,12,13,14,],[9,9,9,9,9,]),'EXIT':([0,11,12,13,14,],[10,10,10,10,10,]),'$end':([0,1,2,3,4,5,10,15,16,17,18,19,20,21,22,23,24,25,27,],[-18,0,-1,-2,-7,-8,-17,-9,-11,-10,-15,-13,-14,-16,-3,-4,-5,-6,-12,]),'MULTIPLY':([2,4,5,10,15,16,17,18,19,20,21,22,23,24,25,27,],[11,-7,-8,-17,-9,-11,-10,-15,-13,-14,-16,-3,-4,11,11,-12,]),'DIVIDE':([2,4,5,10,15,16,17,18,19,20,21,22,23,24,25,27,],[12,-7,-8,-17,-9,-11,-10,-15,-13,-14,-16,-3,-4,12,12,-12,]),'PLUS':([2,4,5,10,15,16,17,18,19,20,21,22,23,24,25,27,],[13,-7,-8,-17,-9,-11,-10,-15,-13,-14,-16,-3,-4,-5,-6,-12,]),'MINUS':([2,4,5,10,15,16,17,18,19,20,21,22,23,24,25,27,],[14,-7,-8,-17,-9,-11,-10,-15,-13,-14,-16,-3,-4,-5,-6,-12,]),'STRING':([6,7,26,],[16,16,16,]),'FALSE':([8,9,],[19,19,]),'TRUE':([8,9,],[20,20,]),'COMMA':([16,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'expression':([0,11,12,13,14,],[2,22,23,24,25,]),'empty':([0,],[3,]),'column':([6,7,26,],[15,17,27,]),'boolean':([8,9,],[18,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','pcs_lexer.py',128),
  ('calc -> empty','calc',1,'p_calc','pcs_lexer.py',129),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression','pcs_lexer.py',136),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','pcs_lexer.py',137),
  ('expression -> expression PLUS expression','expression',3,'p_expression','pcs_lexer.py',138),
  ('expression -> expression MINUS expression','expression',3,'p_expression','pcs_lexer.py',139),
  ('expression -> NUMBER','expression',1,'p_expression_int_float','pcs_lexer.py',146),
  ('expression -> FLOAT','expression',1,'p_expression_int_float','pcs_lexer.py',147),
  ('expression -> TABLE_C column','expression',2,'p_createTable','pcs_lexer.py',154),
  ('expression -> TABLE_R column','expression',2,'p_addRowToTable','pcs_lexer.py',162),
  ('column -> STRING','column',1,'p_Column','pcs_lexer.py',170),
  ('column -> STRING COMMA column','column',3,'p_Column','pcs_lexer.py',171),
  ('boolean -> FALSE','boolean',1,'p_boolean','pcs_lexer.py',183),
  ('boolean -> TRUE','boolean',1,'p_boolean','pcs_lexer.py',184),
  ('expression -> report_item_type_enable boolean','expression',2,'p_report_create_view','pcs_lexer.py',191),
  ('expression -> report_item_enable boolean','expression',2,'p_report_create_view','pcs_lexer.py',192),
  ('expression -> EXIT','expression',1,'p_exit','pcs_lexer.py',199),
  ('empty -> <empty>','empty',0,'p_empty','pcs_lexer.py',206),
]
