
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDEAPPEND BODY CLEAR COLUMN COMMA DIVIDE ELEMENT_GRID_ADD EQUALS EXIT FALSE FLOAT FOOTER HEAD LPAREN MINUS MULTIPLY NUMBER PATHNAME PERIOD PLUS RECEIPT RPAREN SET_CART_QUANTITY_ENABLE SET_CART_ROW_SIZE SET_DIMENSION SET_SHOP_NAME STRING TABLE_C TABLE_R TO TRUE VIEW item_enable item_type_enable\n    calc : expression\n         | tableExp\n         | pathexpr\n         | receiptexpr\n         | mainviewexpr\n         | reportexpr\n         | empty\n    \n    boolean : TRUE\n            | FALSE\n    \n    expression : expression MULTIPLY expression\n               | expression DIVIDE expression\n               | expression PLUS expression\n               | expression MINUS expression\n    \n    expression : NUMBER\n               | FLOAT\n    \n    pathexpr : PERIOD PERIOD DIVIDE pathexpr\n           | PERIOD DIVIDE pathexpr\n           | STRING DIVIDE pathexpr\n           | STRING DIVIDE filename\n    filename : STRING PERIOD STRING\n           | STRING\n    \n    receiptexpr : RECEIPT CLEAR HEAD\n            | RECEIPT CLEAR BODY\n            | RECEIPT CLEAR FOOTER\n    \n    receiptexpr : RECEIPT APPEND STRING TO HEAD\n            | RECEIPT APPEND STRING TO BODY\n            | RECEIPT APPEND STRING TO FOOTER\n    \n    mainviewexpr : VIEW SET_SHOP_NAME STRING\n                | VIEW SET_DIMENSION NUMBER COMMA NUMBER\n                | VIEW SET_CART_ROW_SIZE NUMBER\n                | VIEW SET_CART_QUANTITY_ENABLE boolean\n                | VIEW ELEMENT_GRID_ADD path_series\n    \n    path_series : STRING\n                | STRING DIVIDE STRING\n    \n    tableExp : TABLE_C STRING column\n    \n    tableExp : TABLE_R STRING column\n    \n    column : STRING\n            | STRING COMMA column\n    \n    reportexpr : item_type_enable boolean\n                | item_enable boolean\n    \n    expression : EXIT\n    \n    empty :\n    '
    
_lr_action_items = {'NUMBER':([0,20,21,22,23,32,33,66,],[9,9,9,9,9,57,58,73,]),'FLOAT':([0,20,21,22,23,],[10,10,10,10,10,]),'EXIT':([0,20,21,22,23,],[11,11,11,11,11,]),'TABLE_C':([0,],[12,]),'TABLE_R':([0,],[14,]),'PERIOD':([0,15,25,28,46,50,],[15,27,15,15,63,15,]),'STRING':([0,12,14,24,25,26,28,30,31,35,50,62,63,67,],[13,24,26,44,46,44,13,55,56,61,13,44,69,74,]),'RECEIPT':([0,],[16,]),'VIEW':([0,],[17,]),'item_type_enable':([0,],[18,]),'item_enable':([0,],[19,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,36,37,38,39,40,41,42,43,44,45,46,47,48,49,51,52,53,54,56,58,59,60,61,64,68,69,70,71,72,73,74,],[-42,0,-1,-2,-3,-4,-5,-6,-7,-14,-15,-41,-39,-8,-9,-40,-10,-11,-12,-13,-37,-35,-21,-18,-19,-36,-17,-22,-23,-24,-28,-30,-31,-32,-33,-16,-38,-20,-25,-26,-27,-29,-34,]),'MULTIPLY':([2,9,10,11,40,41,42,43,],[20,-14,-15,-41,-10,-11,20,20,]),'DIVIDE':([2,9,10,11,13,15,27,40,41,42,43,46,61,],[21,-14,-15,-41,25,28,50,-10,-11,21,21,25,67,]),'PLUS':([2,9,10,11,40,41,42,43,],[22,-14,-15,-41,-10,-11,-12,-13,]),'MINUS':([2,9,10,11,40,41,42,43,],[23,-14,-15,-41,-10,-11,-12,-13,]),'CLEAR':([16,],[29,]),'APPEND':([16,],[30,]),'SET_SHOP_NAME':([17,],[31,]),'SET_DIMENSION':([17,],[32,]),'SET_CART_ROW_SIZE':([17,],[33,]),'SET_CART_QUANTITY_ENABLE':([17,],[34,]),'ELEMENT_GRID_ADD':([17,],[35,]),'TRUE':([18,19,34,],[37,37,37,]),'FALSE':([18,19,34,],[38,38,38,]),'HEAD':([29,65,],[52,70,]),'BODY':([29,65,],[53,71,]),'FOOTER':([29,65,],[54,72,]),'COMMA':([44,57,],[62,66,]),'TO':([55,],[65,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'expression':([0,20,21,22,23,],[2,40,41,42,43,]),'tableExp':([0,],[3,]),'pathexpr':([0,25,28,50,],[4,47,51,64,]),'receiptexpr':([0,],[5,]),'mainviewexpr':([0,],[6,]),'reportexpr':([0,],[7,]),'empty':([0,],[8,]),'boolean':([18,19,34,],[36,39,59,]),'column':([24,26,62,],[45,49,68,]),'filename':([25,],[48,]),'path_series':([35,],[60,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','pcs_lexer.py',229),
  ('calc -> tableExp','calc',1,'p_calc','pcs_lexer.py',230),
  ('calc -> pathexpr','calc',1,'p_calc','pcs_lexer.py',231),
  ('calc -> receiptexpr','calc',1,'p_calc','pcs_lexer.py',232),
  ('calc -> mainviewexpr','calc',1,'p_calc','pcs_lexer.py',233),
  ('calc -> reportexpr','calc',1,'p_calc','pcs_lexer.py',234),
  ('calc -> empty','calc',1,'p_calc','pcs_lexer.py',235),
  ('boolean -> TRUE','boolean',1,'p_boolean','pcs_lexer.py',242),
  ('boolean -> FALSE','boolean',1,'p_boolean','pcs_lexer.py',243),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression','pcs_lexer.py',250),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','pcs_lexer.py',251),
  ('expression -> expression PLUS expression','expression',3,'p_expression','pcs_lexer.py',252),
  ('expression -> expression MINUS expression','expression',3,'p_expression','pcs_lexer.py',253),
  ('expression -> NUMBER','expression',1,'p_expression_int_float','pcs_lexer.py',260),
  ('expression -> FLOAT','expression',1,'p_expression_int_float','pcs_lexer.py',261),
  ('pathexpr -> PERIOD PERIOD DIVIDE pathexpr','pathexpr',4,'p_pathexpr','pcs_lexer.py',268),
  ('pathexpr -> PERIOD DIVIDE pathexpr','pathexpr',3,'p_pathexpr','pcs_lexer.py',269),
  ('pathexpr -> STRING DIVIDE pathexpr','pathexpr',3,'p_pathexpr','pcs_lexer.py',270),
  ('pathexpr -> STRING DIVIDE filename','pathexpr',3,'p_pathexpr','pcs_lexer.py',271),
  ('filename -> STRING PERIOD STRING','filename',3,'p_pathexpr','pcs_lexer.py',272),
  ('filename -> STRING','filename',1,'p_pathexpr','pcs_lexer.py',273),
  ('receiptexpr -> RECEIPT CLEAR HEAD','receiptexpr',3,'p_receiptexpr_creat','pcs_lexer.py',280),
  ('receiptexpr -> RECEIPT CLEAR BODY','receiptexpr',3,'p_receiptexpr_creat','pcs_lexer.py',281),
  ('receiptexpr -> RECEIPT CLEAR FOOTER','receiptexpr',3,'p_receiptexpr_creat','pcs_lexer.py',282),
  ('receiptexpr -> RECEIPT APPEND STRING TO HEAD','receiptexpr',5,'p_receiptexpr_append','pcs_lexer.py',289),
  ('receiptexpr -> RECEIPT APPEND STRING TO BODY','receiptexpr',5,'p_receiptexpr_append','pcs_lexer.py',290),
  ('receiptexpr -> RECEIPT APPEND STRING TO FOOTER','receiptexpr',5,'p_receiptexpr_append','pcs_lexer.py',291),
  ('mainviewexpr -> VIEW SET_SHOP_NAME STRING','mainviewexpr',3,'p_mainviewexp','pcs_lexer.py',299),
  ('mainviewexpr -> VIEW SET_DIMENSION NUMBER COMMA NUMBER','mainviewexpr',5,'p_mainviewexp','pcs_lexer.py',300),
  ('mainviewexpr -> VIEW SET_CART_ROW_SIZE NUMBER','mainviewexpr',3,'p_mainviewexp','pcs_lexer.py',301),
  ('mainviewexpr -> VIEW SET_CART_QUANTITY_ENABLE boolean','mainviewexpr',3,'p_mainviewexp','pcs_lexer.py',302),
  ('mainviewexpr -> VIEW ELEMENT_GRID_ADD path_series','mainviewexpr',3,'p_mainviewexp','pcs_lexer.py',303),
  ('path_series -> STRING','path_series',1,'p_path_series','pcs_lexer.py',310),
  ('path_series -> STRING DIVIDE STRING','path_series',3,'p_path_series','pcs_lexer.py',311),
  ('tableExp -> TABLE_C STRING column','tableExp',3,'p_createTable','pcs_lexer.py',323),
  ('tableExp -> TABLE_R STRING column','tableExp',3,'p_addRowToTable','pcs_lexer.py',332),
  ('column -> STRING','column',1,'p_Column','pcs_lexer.py',340),
  ('column -> STRING COMMA column','column',3,'p_Column','pcs_lexer.py',341),
  ('reportexpr -> item_type_enable boolean','reportexpr',2,'p_report_create_view','pcs_lexer.py',361),
  ('reportexpr -> item_enable boolean','reportexpr',2,'p_report_create_view','pcs_lexer.py',362),
  ('expression -> EXIT','expression',1,'p_exit','pcs_lexer.py',372),
  ('empty -> <empty>','empty',0,'p_empty','pcs_lexer.py',379),
]
